# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-01 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_url', models.URLField()),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('output_url', models.URLField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark', models.DateTimeField()),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Bookmark')),
            ],
        ),
    ]
