# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-01 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='output_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
